#!/usr/bin/env zsh
typeset -a shCommands=($(command jenv commands --sh))

typeset IFS="|"
typeset fnText="
function jenv {
  typeset command=\"\$1\"

  if [ \"\$#\" -gt 0 ]; then
    shift
  fi

  case \"\$command\" in
  ${shCommands[*]})
    eval \`jenv \"sh-\$command\" \"\$@\"\`;;
  *)
    command jenv \"\$command\" \"\$@\";;
  esac
}"

eval "${fnText}"

jenv "$@"