#!/usr/bin/env zsh

typeset -A machine_aliases

zstyle -a ':prezto:module:host-alias' machines 'machine_aliases'
typeset hostname=${HOST%\.*}
typeset hostAlias=${machine_aliases[${hostname}]:-${hostname:0:1:u}${hostname:1}}

eval "
prompt_host_alias() {
  p10k segment -f 208 -t \"${hostAlias}\"
}"

prompt_host_alias "$@"