#!/usr/bin/env zsh

typeset -A machine_aliases

zstyle -a ':prezto:module:host-alias' machines 'machine_aliases'
typeset hostAlias=${machine_aliases[${HOST}]:-${HOST:0:1:u}${HOST:1}}

eval "
prompt_host_alias() {
  p10k segment -f 208 -t \"${hostAlias}\"
}"

prompt_host_alias "$@"