#!/usr/bin/env zsh
#function glogout {
    typeset repo=${1:-${DEFAULT_REPO}}

    sudo security -q delete-internet-password -s "${repo}" 2> /dev/null

    git credential-cache exit
    git config --system --unset credential.helper
    git config --global --unset credential.helper
    git config --global credential.helper 'cache --timeout 28800'
#}
