#!/usr/bin/env zsh
rm -rf "${ZDOTDIR:-$HOME}/.zcompdump"{,.zwc} "${XDG_CACHE_HOME:-$HOME/.cache}/prezto/zcomp"{cache,dump}
autoload -Uz compinit

typeset dumpFile="${XDG_CACHE_HOME:-$HOME/.cache}/prezto/zcompdump"
compinit -C -d "${dumpFile}"
zcompile "${dumpFile}"