#!/usr/bin/env zsh
#function updateModules {
  typeset -a modules user_module_dirs
  zstyle -a ':prezto:load' pmodule 'modules'
  zstyle -a ':prezto:load' pmodule-dirs 'user_module_dirs'

  for module in "${modules[@]}"; do
    typeset -a locations=(${user_module_dirs:+${^user_module_dirs}/$module(-/FN)})
    if (( ${#locations} != 1 )); then
      continue
    fi

    typeset upgradeScript=${locations[-1]}/upgrade.zsh

    if [[ -s ${upgradeScript} ]]; then
      stageTitle "Updating module ${module}"
      source "${upgradeScript}"
    fi
  done
#}